//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.FTC_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FTC_Service.IFTCService")]
    public interface IFTCService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFTCService/CelsiusToFahrenheit", ReplyAction="http://tempuri.org/IFTCService/CelsiusToFahrenheitResponse")]
        double CelsiusToFahrenheit(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFTCService/CelsiusToFahrenheit", ReplyAction="http://tempuri.org/IFTCService/CelsiusToFahrenheitResponse")]
        System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFTCService/FahrenheitToCelsius", ReplyAction="http://tempuri.org/IFTCService/FahrenheitToCelsiusResponse")]
        double FahrenheitToCelsius(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFTCService/FahrenheitToCelsius", ReplyAction="http://tempuri.org/IFTCService/FahrenheitToCelsiusResponse")]
        System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double celsius);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFTCServiceChannel : ClientApp.FTC_Service.IFTCService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FTCServiceClient : System.ServiceModel.ClientBase<ClientApp.FTC_Service.IFTCService>, ClientApp.FTC_Service.IFTCService {
        
        public FTCServiceClient() {
        }
        
        public FTCServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FTCServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FTCServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FTCServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CelsiusToFahrenheit(double celsius) {
            return base.Channel.CelsiusToFahrenheit(celsius);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsius) {
            return base.Channel.CelsiusToFahrenheitAsync(celsius);
        }
        
        public double FahrenheitToCelsius(double celsius) {
            return base.Channel.FahrenheitToCelsius(celsius);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double celsius) {
            return base.Channel.FahrenheitToCelsiusAsync(celsius);
        }
    }
}
